[tool.poetry]
name = "ask-me"
version = "0.1.0"
description = "Explain exceptions using OpenAI"
authors = ["RA <numpde@null.net>"]
readme = "README.md"
packages = [{include = "ask_me"}]

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
